services:
  - type: web
    name: konai-news
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
